### ISSUE TITLE
Plotting Data- Basic R Assignment

### ISSUE THREAD

**Issue by kristinlinesch** [dmcglinn/quant_methods#10]
I am having trouble accurately plotting the data for questions 5 and 6 on the Basic R Assignment. I named the data "plant".

I've written the following R code for question 5:

```{r}
plot(plant$scale,plant$richness, xlab='Scale',ylab='Richness',col='blue')
```

And the following code for question 6:

```{r}
plot(plant$scale,plant$richness,log='xy',xlab='Scale',ylab='Richness',col='blue')
```

Ive attached the two jpegs of the graphs that came out. These dont seem like great depictions. I've tried other code like boxplot, xyplot, etc. but these look funky too. I also looked at the code  in the Lesson section for #Plotting Data, but when I replicate that code for this data, it doesn't look any better. Any suggestions on how to better represent the data here? 

![rplot1](https://cloud.githubusercontent.com/assets/16704439/12326583/b9dbc2fc-ba9f-11e5-855d-594fa675e47f.jpeg)
![rplot2](https://cloud.githubusercontent.com/assets/16704439/12326584/bbca0f42-ba9f-11e5-8071-faabffb9d694.jpeg)

**Comment by Jordylacrosse** [comment]
Hi Kristin and class,
I got the same graphs that you got as well- I even played around with the range of the richness tick marks and couldn't get it to work either (because the richness y tick marks don't appear evenly dispersed to me.) But I couldn't figure it out and kept coming back to these . I assumed that when applying the log=xy function, it came out clearer and it was correct- there is a trend easily seen...but I agree, I was expecting a clear/concise plot as well. Below is the code I used. 

scale<-tgpp.data[ ,"scale"]
scale
richness<-tgpp.data[,"richness"]
richness

plot(richness~scale, data=tgpp.data, xlab='scale', ylab='richness',col=4)
plot(richness~scale, data=tgpp.data, xlab='scale', ylab='richness',log='xy',col=4)

**Comment by dmcglinn** [comment]
Hey @kristinlinesch and @Jordylacrosse thanks so much for this question. I think you code looks great, but you're correct this is not necessary the best way to display the results. Clearly there is uncertainly around the value of richness at a particular scale. One way to better illustrate
this would be to use box and whisker plots to summarize the quantiles of richness for each scale

```{r coffee} 
png('../figures/scale_vs_rich_loglog_box.png')
boxplot(log10(richness) ~ log10(scale), data=dat, 
        xlab=expression(log[10]*scale (m^2)), ylab=expression(log[10]*richness))
```

So that provides a better summary of the uncertainly but is still a little difficult to gauge the geometry or
shape of the trend.
To accomplish that is is useful to add a line to the average richness at each scale
``` {r coffee}
rich_avg = tapply(dat$richness, dat$scale, mean)
scales = as.numeric(names(rich_avg))
plot(log10(scales), log10(rich_avg), lwd=2, col='red', type='o',
     xlab=expression(log[10]*scale (m^2)), ylab=expression(log[10]*richness))
dev.off()
```

We can see the pattern is concave down in log log space and now linear as expected by a power law relationship for example. This plot is good for shape but we don't have any info on uncertainly. Is there a way we can combine both? This may be more difficult then is looks unfortunately. Any other suggestions out there?

**Comment by walkermf** [comment]
Hi,

I am trying to add the line showing the overall trend onto the boxplots so you will be an idea of the shape as well as uncertainty.  I plotted the line graph and then added the argument add=T to the boxplot.  However, I cannot get the two graphs to line up correctly.  

Here is the code I have: (I am on a different computer so I will just have to paste the code and attach the graph)

tgpp<-read.csv("http://dmcglinn.github.io/quant_methods/data/tgpp.csv", header=T)
richavg<-tapply(tgpp$richness, tgpp$scale, mean)
scales<-as.numeric(names(richavg))
plot(log10(richavg)~log10(scales), lwd=2, col="red", type="o", xlab=expression(log[10]*scale(m^2)),ylab=expression(log[10]*richness))
boxplot(log10(richness)~log10(scale),data=tgpp, xlab=expression(log[10]*scale(m^2)), ylab=expression(log[10]*richness), add=T)


[Rplot.pdf](https://github.com/dmcglinn/quant_methods/files/90991/Rplot.pdf)
 
Let me know if y'all think this is the right direction and if you know of a way to fix the issue!

Margaret

**Comment by dmcglinn** [comment]
Thanks @walkermf for taking a crack at that. You're definitely on the right track. If we look at `?boxplot` you can find this definition for the argument "at": _*numeric vector giving the locations where the boxplots should be drawn, particularly when add = TRUE; defaults to 1:n where n is the number of boxes.*_ So your graphic was basically trying to put boxes on the values 1-5. Here I've just added the at argument and cleaned things up a little bit: 

```{r}
# we'll start with the same plot as just above but use type='n' so 
# that only the graphic is setup but no data is plotted
plot(log10(scales), log10(rich_avg), type='n', ylim=range(log10(dat$richness), finite=T),
     xlab=expression(log[10]*scale (m^2)), ylab=expression(log[10]*richness))
# then we add the boxplots. The critical new arguments here are "add"
# and "at" where you specify the placement of the boxplots along
# the x-axis. Also note the use of boxwex to scale down the width 
# of the boxplots so they fit better 
boxplot(log10(richness) ~ log10(scale), data=dat, add=T,
        at = log10(scales), boxwex=0.25)
# finally we add the richness averages over the top of the boxplots
lines(log10(scales), log10(rich_avg), lwd=2, col='red', type='o')
```

Now we have a visual representation that summarizes quite a bit of information. The box-and-whiskers provide the interquartile range, the red dots are the averages which nicely show the changes in relative slope between various scales. Clearly we have greater uncertainly in richness as small scales and richness is accumulated more rapidly at these scales.

**Comment by TomNash** [comment]
Was just about to comment about `boxwex` after I noticed the difference in distance between the x-axes caused by the width of the boxes. I was able to put points at the means
![image](https://cloud.githubusercontent.com/assets/8193065/12344708/6f82bfb6-bb0e-11e5-8923-d16f4b54f43d.png)
and get the line in the same plot but the axes were still wrong.
![image](https://cloud.githubusercontent.com/assets/8193065/12344731/989ff7f6-bb0e-11e5-9e49-2630d465c537.png)

**Comment by dmcglinn** [comment]
nice @TomNash can you please share your code with the group. Format it just as you would in an Rmarkdown doc with the "```{r}" tags.

**Comment by TomNash** [comment]
There we go.
```
boxplot(log10(richness) ~ log10(scale), data=dat, xlab=expression(log[10]*scale (m^2)),
     ylab=expression(log[10]*richness))
lines(log10(rich_avg),col='red')
points(log10(rich_avg),col='red')
```
![image](https://cloud.githubusercontent.com/assets/8193065/12345328/7909eae4-bb15-11e5-9713-0321abcdb4c1.png)

**Comment by dmcglinn** [comment]
@TomNash's suggestion is definitely the simplest and therefore the best but I'm not sure why it works...?

**Comment by dmcglinn** [comment]
that's how R is though sometimes you leave scratching your head - this is true for many other computer programming languages as well.
