### ISSUE TITLE
y[i] expression problem

### ISSUE THREAD

**Issue by mikala-randich** [dmcglinn/quant_methods#13]
``` r
y=0
x=1:10
for(i in 1:10) {
  y[i] = x[i] + sum(x[1:i]) + 1
  if (y[i]<=10) {
    print(y)
  }
  else if (y[i]>10) {
    print ('NA')
  }
}
y
```

Hi everyone, this is what I have so far. The problem I'm having is that the y[i] output starts at 3 instead of 1, so I think there's a problem with my y[i] expression. Any ideas? (output below)
[1] 3
[1] 3 6
[1]  3  6 10
[1] "NA"
[1] "NA"
[1] "NA"
[1] "NA"
[1] "NA"
[1] "NA"
[1] "NA"

**Comment by TomNash** [comment]
You're really close, the answer is there in your code. Try getting a sheet of paper and doing a variable trace of what you have now. So it'll look something like this, but fill in the values as necessary. Hopefully you can see the problem through this and you can correct the code you have. Also I would set the value of `y[i]` to `NA` where it's greater than 10 instead of simply printing.

```
i     x[i]    x[1:i]    sum(x[1:i])     x[i] + sum(x[1:i]) + 1
--------------------------------------------------------------
1      1        1            ?                    ?
2      2        1 2          ?                    ?

...

10     ?        ?            ?                    ?
```

**Comment by congeram** [comment]
I ran into the same issues and what I did is i forced the first component of y[1] to be 1 and then set my counter to start later. I could then achieve the same thing by forcing my counter to start at 0 (because thats what I'm used to in python) without needing to give the initial value anymore

**Comment by dmcglinn** [comment]
thanks for all the great comments folks! I really like @TomNash 's suggestion of a variable trace. Instead of staring at your code you could take a step back and try to write out the algebra of what you are trying to accomplish for each value of y. This should help you to come to a general formula that you can easily code. One quick question @mikala-randich why do you think you need this block of code: 

``` r
  if (y[i]<=10) {
    print(y)
  }
  else if (y[i]>10) {
    print ('NA')
  }
```

**Comment by dmcglinn** [comment]
@congeram do you want to share your code with us here? It is difficult to picture what you are saying. Did your solution work?

**Comment by mikala-randich** [comment]
Thanks @TomNash , that was a great help, I fixed the code. @dmcglinn That was my attempt to address question 6, where the output should be NA if the sum is >10

**Comment by dmcglinn** [comment]
oh yea my bad. Awesome glad it's working. There is definitely more than one way to code this thing.

**Comment by walkermf** [comment]
You could also change your for loop to be for i in x and then just run the sum function on x. This will sum the values in x for each iteration.

**Comment by congeram** [comment]
```
y=0
x=c(1:10)
for (i in 0:11) { 
   y[i] = x[i]+sum(x[1:i-1])
}
y
```

**Comment by walkermf** [comment]
Sorry I am trying to comment from my phone.  I really meant: 
'''{r}
x = NULL
for(i in x){
    s = sum(1:i) 
 

And so on...

**Comment by walkermf** [comment]
One more try haha... I am on the actually computer now.

'''{r}
y=c()
for(i in 1:10){
  s= sum(1:i)
  print(s)
}
'''
