### ISSUE TITLE
nano pc install failures

### ISSUE THREAD

**Issue by dmcglinn** [dmcglinn/quant_methods#14]
Hey folks I just wanted to share with you the following new instructions that I was able to use to get nano installed on a pc:

Download the program from here: 
http://www.nano-editor.org/dist/v2.2/NT/nano-2.2.6.zip
Unzip the file and paste the files that have either a .exe or .dll extension in the directory: `C:/Windows/System32/`

If none of the files appear to have a .exe file ending look for the file called `nano` (this also indicates to me that you must have the default windows option of hiding file extensions active - go turn it off when you get a chance).  

Restart the terminal and try the command `winpty nano test.txt` 
If everything is working this will create a file called test.txt in your working directory  for you to edit within the terminal.

**Comment by dmcglinn** [comment]
I should also note that it is not necessary to use nano and that you can do just fine with notebook when using git at the command line.

**Comment by zachbjur** [comment]
I just tried this, and initially it worked. nano came up when I used the command `winpty nano test.txt` but when I tried the command `nano mars.txt` the console gave me the message "Redirection is not supported"

**Comment by dmcglinn** [comment]
That's correct without the `winpty` command this will not work which is a bummer. Apparently the developers of git for windows changed some core pieces and it created an incompatibility with `nano`.  I apologize to those of you that were wrestling with this in class.

**Comment by Jordylacrosse** [comment]
I was able to finally get nano installed and I was able to get through the first part of the lesson with setting up a git. ( I was running into the same problem  as Zach when running nano, I have to type  winpty nano test.txt in order to get nano to work).  But after I have gotten through this, I have tried to create a directory for planets, and when doing such I get an error message saying:
" mkdir: cannot create directory ‘planets’: Permission denied" or even trying the function $ git init, it also replies with the error message: Permission denied. This follows for several other commands I type into git..

Is this another issue associated with the nano download or am I missing something?

Thanks,

Jordy

**Comment by dmcglinn** [comment]
Try doing those commands with "sudo" at the front of the command. I'm not sure why but those errors are informing you that you don't have the user privileges to do those commands. After running a command with sudo you will be prompted for your password. 

Dan

**Comment by Jordylacrosse** [comment]
Still no luck, I get the response "sudo" not found. Even after trying it still denied me. (even though I am the only and main owner with privileges on this computer..) 
I even tried the commands: elevated, su, admin, and runas to set me as an administrator...No luck.
