### ISSUE TITLE
metaMDS issue

### ISSUE THREAD

**Issue by shoresk** [dmcglinn/quant_methods#25]
I'm having trouble getting an ordination plot going for part of my data. 
I put together some of the columns I want to look at: 

`CTD_env = CTD_June$Latitude + CTD_June$Depth + CTD_June$Salinity + CTD_June$Temperature`

And tried out an MDS: 
`library(vegan)
library(dummies)
CTD_mds = metaMDS(CTD_env)`

But get this error: 

> Error in if (inherits(comm, "dist") || ncol(comm) == nrow(comm) && all(comm ==  : 
>   missing value where TRUE/FALSE needed

I need to figure out where the TRUE/FALSE is needed, and probably do something with the data. Any help?

**Comment by dmcglinn** [comment]
Hey @shoresk. There are a couple problems here. First in defining `CTD_env` you have specified it as the sum of all of those variables. I think you wanted something like:

```
CTD_env = CTD_June[ , c('Latitude', 'Depth', 'Salinity', 'Temperature')]
```

Second MDS is not the appropriate analysis for a multivariate analysis of continuous environmental variables because is this context we almost always are interested in Euclidean distances whereas MDS is designed for non-Euclidean distances (e.g., bray-curtis, jaccard, etc). Principle components analysis (PCA) is the appropriate multivariate method to use in this context. You can use the `vegan` function `rda(CTD_env)` to run a PCA. Also the package `dummies` is only helpful when converting factors into dummy matrices (i.e., 0/1 matrices where each level of the factor is a different column).

**Comment by shoresk** [comment]
Thanks, I fixed the CTD_env and used an rda: 
`library(vegan)`
CTD_env = CTD_June[ , c('Latitude', 'Depth', 'Salinity', 'Temperature')]
CTD_rda = rda(CTD_env, skip = 2)
plot(CTD_rda)`

But I get this error message: 

> CTD_rda = rda(CTD_env, skip = 2)
> Error in colMeans(x, na.rm = TRUE) : 'x' must be numeric
> plot(CTD_rda)
> Error in plot(CTD_rda) : object 'CTD_rda' not found

**Comment by dmcglinn** [comment]
I think one of your variables may be a factor or string. Depth seems like the best candidate. Also I'm not sure why you supplied the argument `skip` to the function `rda`? This function doesn't seem to have this as an argument. What does this return: 

```
sapply(CTD_env, class)
```
