### ISSUE TITLE
Q4: Clarification and Approach

### ISSUE THREAD

**Issue by knuthfa** [dmcglinn/quant_methods#3]
Clarification: What exactly is mean by environmental information? Is it columns elev, tci, streamdist, disturb and beers (definitely beers) or just a few of those or just beers? 

Approach: Am wondering what approach to take here. I explored the data using the following operations.

elev = with(trees, tapply(elev, plotID, FUN = function(x) unique(x)))
tci = with(trees, tapply(tci, plotID, FUN = function(x) unique(x)))
streamdist = with(trees, tapply(streamdist, plotID, FUN = function(x) unique(x)))
disturb = with(trees, tapply(disturb, plotID, FUN = function(x) unique(x)))
beers = with(trees, tapply(beers, plotID, FUN = function(x) unique(x)))

Then used View() to look and scroll through the newly created data variables. It seems in some cases, for example, a given Plot might have more than one elevation listed with it. So does this mean that our final data frame will have 935 (#of unique plots) with multiple entries for a given cell within a column, such as elevation? I can easily visualize that in excel but I have no idea how to express it in R.

**Comment by dmcglinn** [comment]
By environmental variables I was thinking about the variables: elev, tci, streamdist, disturb. and beers. But I think you could also make the argument for including the utm variables as well which likely act as good proxies for environmental variation or at least geographic differences. 

Your approach has a few key problems. From the outset one of the most important problems is again you are breaking up the relationship between the columns of the `trees` data.frame. Remember basically what you are trying to do is just pull out a subset of the rows of `trees` just as we did in the species subsetting portions but now we are focused on a single row for each unique plot id. At a minimum it will be straightforward to identify these rows using a for loop, but I like that you are attempting to be a bit more sophisticated by using a tapply() function; however, in this case I'm not sure its going to help so much. 

Really the key to this problem is in part solved by the work you did to answer Q2. Your description of the richness variable that you created #2 suggests that you basically have all the information you need to carry out a successful merging of the new richness variable with the full `trees` data.frame. Take a look at what the following returns `names(richness)`. Now that you can access that information could you build a data.frame that has plotID and richness ? This would be ideal because it is exactly what you will want if when using `merge()`. Also be sure to pay attention to the merge arguments `all.x`, `all.y`, and `all`. However all that being said I'm only leading you down one of many different paths you could potentially take. However, this path I have found is the least prone to errors and the easiest to code. Good luck!

**Comment by knuthfa** [comment]
Let me start with trying to merge richness back into trees by plotID without using a for loop, which I gather from your previous response is a valid and possibly most robust approach. 

richness doesn't seem to have any columns, which is what I think is preventing me from merging it back into trees by plotID:

colnames(richness)
Error in dn[[2L]] : subscript out of bounds

names(richness) simply gives me a list of all plotID's in richness. In View(richness) I see plotID's in one column headed "row.names" and species counts in another columns headed "x". But colnames(richness) gives me an error, which implies these aren't actually columns. class(richness) tells me it is an array, which should be able to have columns? If not, do I need to convert it to a data.frame first? I tried as.data.frame(richness), but that doesn't seem to have permanently converted it, as I am still getting the same errors listed above.

Also tried just flat out renaming row.names with

names(richness)[names(richness)=="row.names"] = "plotID"

which runs without error but doesn't seem to do anything.

**Comment by dmcglinn** [comment]
Your barking up all the right trees just haven't quite nailed it down yet. You are correct in that richness isn't a `data.frame` and that the function `merge()` requires that the two objects to be merged are data.frames (see `?merge` for more info). So yep you're going to have to convert richness into a `data.frame` and ideally really what you want is a two column `data.frame`: one column for plotID and one column for richness. To make a `data.frame()` from scratch in R try the following:
```
rich_dat = data.frame(plotID = x, rich = richness)
```
Any ideas what you would put in place of `x` in the R code above?

**Comment by knuthfa** [comment]
`names(richness)` ? seems to have worked! I think I've gotten through everything up until Q5. I will close this and open a new issue for it. Thx!
