### ISSUE TITLE
Creating a Community Matrix

### ISSUE THREAD

**Issue by strangebb** [dmcglinn/quant_methods#46]
Hey for my R project I'm trying to create a community matrix from a tabular set of data and I'm not sure what I'm doing wrong. Each row in the data set corresponds to a fish that was caught in a particular sample site. The data doesn't have totals for each species in each site, so I'm trying to create a community matrix with a row for each sample site and a column with each unique species, but I'm not sure how to set the parameters in the for loop to achieve this. 

This is what I've got so far for setting up the matrix:

```r
uni_sp = unique(BullsBay16_18$Species)
uni_site = unique(BullsBay16_18$Location)
comm = matrix(0, ncol=length(uni_sp), nrow=length(uni_site))
colnames(comm) = uni_sp
rownames(comm) = uni_site 
```
I'm trying to write a for loop that will fill in the community matrix by sequencing through each site and counting the number of occurrences of each species, and this is what I've got so far for setting up the for loop:

```r
for(i in seq_along(uni_sp)) {
    for(j in seq_along(uni_site)) {
       comm[j , i] = count(BullsBay16_18$Location == uni_site[j],
                                        BullsBay16_18$Species == uni_sp[i]) 
   }
}


This gives an error message:

"Error in UseMethod("as.quoted") : no applicable method for 'as.quoted' applied to an object of class "logical""

Thanks in advance!

**Comment by dmcglinn** [comment]
Hey @strangebb thanks for this question. First just a quick note that I edited your quesiton so that the code blocks were properly formatted (take a look on github if you want to see what I changed). More to your question though the mistake that you made is that you need subset both the site and the species of `BullsBay16_18` simultaneously as a joined subset rather that as two independent queries. Also there is no function `count` at least in base R (maybe you have a package loaded) usually we just use the function `length` to tell us how many of something there is unless its rows or columns then `nrow` and `ncol` are helpful. 

Here is what I would suggest using base R with a for loop as you’ve setup above

`comm[j, i] = with(BullsBay16_18, nrow(BullsBay16_18[Location == uni_site[j] & Species == uni_sp[i]))`

The above should work I think. Several things to note here the function `with` essentially makes the columns of `BullsBay16_18` available to call without having to reference this data.frame first. Also note the placement of the brackets wrapping the two conditional statements which are joined by an AND sybmol do say it must be this site and this species. Here is alternative approach you could take that avoids the loop (see solutions page on multivariate HW for this)

```r
comm = with(BullsBay16_18, tapply(Species, list(Species, Location), length))
comm = ifelse(is.na(comm), 0, comm)
```

Do any of the `dplyr` fans want to suggest an even more human readable bit of code to generate this matrix using pipes?

**Comment by czwartackisr** [comment]
I'm a big fan of the tidyverse, which we've talked a little in class about.  Both the "tidyr" and "dplyr" libraries found within the tidyverse suite of packages are pretty awesome for data wrangling.  I'm pretty sure all of the packages holding the various libraries (ggplot, dplyr, tidyr, readr, etc...) in the tidyverse can be installed by running _install.packages("tidyverse")_.  [I would suggest checking out this cheat sheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf), which surprisingly covers a lot.  The tidyverse wasn't nearly as intimidating to me as base r.   

I think the following may be a solution to your questions.  I'm stealing this from the first panel of the cheat sheet above and changing the variables and objects to your stuff.  The example on the cheat sheet gets a mean of a continuous variable though, while you are trying to get a length (or count) of a nominal datatype (locations).   I'm pretty sure the following works, but I won't be able to run the code without your data.  If you're into sharing it, I'd be happy to though.  

```{r}
#install_packages("tidyverse")
#Just erase the # from above to install packages

library(dplyr)
```
```{r}
bulls = `read.csv("BullsBay16_18.csv")
#read in your data

bulls_abundance = bulls %>%
      group_by(Location) %>% 
      summarise(abun = length(species)) %>%
      arrange(abun) 
#group by location should give you rows 
#summarise I think by length of species 
#then arrange by abun - maybe species if abundance works funky?

bulls_abundance 
#See if it worked here!
```
Let me know if it worked!
Stevie
