### ISSUE TITLE
Numerical Coding Issue

### ISSUE THREAD

**Issue by ckwoodru** [dmcglinn/quant_methods#47]
Hi all,

Still trying to change these Likert-scale survey questions into numbers 1-7 and started with this code:

```r
code_resp <- function(q) {
  if(q == 'Strongly Agree')
     out = 7
  else if (q == 'Agree')
    out = 6
  else if (q == 'Somewhat Agree')
    out = 5
  else if (q == 'Neither agree nor disagree')
    out = 4
  else if (q == 'Somewhat Disagree')
    out = 3
  else if (q == 'Disagree')
    out = 2
  else if (q == 'Strongly Disagree')
    out = 1
  else 
     out = NA
  return(out)}

code_resp(myData_sub$Q5)
```
But the error message I get is:
 `the condition has length > 1 and only the first element will be used`

Anyone see what I did wrong here?

**Comment by czwartackisr** [comment]
I think maybe something like this for each of the categories...

`mydata$code_resp[mydata$code_resp=="Strongly Agree" <- 7`

Maybe in the tidyverse:
```r
install.packages("tidyverse")
library(dplyr)
mydata = mydata %>%
    recode(code_resp, "Strongly Agree" = "7") %>%
    recode(code_resp, "Agree" = "6") %>%
    recode(code_resp, "Somewhat Agree" = "5") %>% 
    recode(code_resp, "Neither agree nor disagree" = "4") %>%
    recode(code_resp, "Somewhat Disagree" = "3") %>%
    recode(code_resp, "Disagree" = "2") %>%
    recode(code_resp, "Strongly Disagree" = "1") 
```

Let me know if it worked!

**Comment by dmcglinn** [comment]
Thanks @czwartackisr for the `dplyr` suggestion here. @ckwoodru the reason you got that error is because the function will only work when it is currently supplied just a single value for the `q` argument. So either you need to apply the function to the column or vector you are interested in supplying the function like  `sapply(myData_sub$Q5, code_resp)` or internally in the function `code_resp` you need to tell it to iterate from the start to the end of the argument `q` using a for loop or other such iterative programming structure. 
For example
```r
code_resp <- function(q) {
  out = vector('numeric', length(q))
  for (i in seq_along(q)) { 
    if(q[i] == 'Strongly Agree')
     out[i] = 7
    else if (q[i] == 'Agree')
      out[i] = 6
    .
    .
    .
  }
  return(out)}
}
```

I applaud your usage of functions but in cases like this where I'm trying to map many different options to a different value I often find that it is more useful to create a data.frame that is the key and then just use `match` to perform the conversion. So for example in this case I would have the following: 

```r
code_key = data.frame(code = c('Strongly Agree', 'Agree', 'Somewhat Agree', 
                               'Neither agree nor disagree', 'Somewhat Disagree', 
                               'Disagree', 'Strongly Disagree'), 
                      value = 7:1)

q5_value = code_key$value[match(my_data$q5, code_key$code)]
```

Maybe the best hybrid approach would be to have a function as follows: 

```r
code_resp <- function(code) {
  code_key = data.frame(code = c('Strongly Agree', 'Agree', 'Somewhat Agree', 
                                 'Neither agree nor disagree', 'Somewhat Disagree', 
                                 'Disagree', 'Strongly Disagree'), 
                        value = 7:1)
  code_value = code_key$value[match(code, code_key$code)]
  return(code_value)}
}
```
To me this is a nice balance of being modular and therefore easy to deploy for other functions and it is easier to read and potentially modify if you want to quickly change it for example make two coding levels the same value.
