### ISSUE TITLE
#7 on the intermediate assignment

### ISSUE THREAD

**Issue by millertp1** [dmcglinn/quant_methods#58]
Place your for loop into a function that accepts as its argument any vector of arbitrary length and it will return y.

I'm not sure what the question is asking me to do

**Comment by eeparsons42** [comment]
From what I understand, it's asking us to place the loop we already made in a function that will do the sum of sequences for a vector of any length. So, the loop we made before only does this for a vector of 10 observations. You have to modify the loop so that it works with vectors of any length, and place it in a function that will accept as it argument these vectors and outputs the sum of sequence values the same as the previous loops did (y) for these different vectors. I think? 

Sorry if I'm wrong or that didn't make any sense. Let me know if I'm way off the mark.

**Comment by mosscr** [comment]
I'm also having trouble with this one. I understand what it is asking for, but I have not the faintest idea of how I would go about getting it.

**Comment by jgcaughro** [comment]
For this question I’d take a second look at the last section of the R intermediate lesson where it talks about functions and how to include for loops in them!

**Comment by dmcglinn** [comment]
Thanks @jgcaughro for giving some tips here. Yea so what we're looking for is some function that provides the arguments to the loops. This is helpful because it makes the loop more modular and easy to use in different contexts

```r
sum_seq <- function( your_functions_arguments_go_here) {
    output <- NULL
    for(i in 1:n) { 
       ...  # some stuff you want to iterate over
     }
     output
}
