### ISSUE TITLE
Modeling with wide format data

### ISSUE THREAD

**Issue by reisenfeldk** [dmcglinn/quant_methods#61]
I understand how to do this assignment for long length data (subset and run lm, glm, and anova), but I don't understand how to run models with the tapply and aggregate data sets created in class.  The way I have them formatted is by individual plot ID with data for each.  I don't understand how to run a model to compare all of them if they are all independent measurements.  Anyone have any advice?  Here is how my new data sets look for reference. 

<img width="684" alt="Screen Shot 2020-02-02 at 2 22 57 PM" src="https://user-images.githubusercontent.com/59877894/73613837-8aefc800-45c7-11ea-8332-764936d2ed83.png">
<img width="559" alt="Screen Shot 2020-02-02 at 2 22 49 PM" src="https://user-images.githubusercontent.com/59877894/73613841-8e834f00-45c7-11ea-9af7-2d5754ff453e.png">

**Comment by dmcglinn** [comment]
hey @reisenfeldk it appears based on your images that you were successful at transforming the tree species cover values from the long format to a two way table of plot ids versus species ids. So nice job on that. For the future, it is usually easier to know what you're working with or where you're having trouble if you go ahead and post the code you used so that we can see exactly where you are getting hung up. The next step to prep the data for modeling is to filter the tree cover data down to just the two columns of interest one for acerrub and one for abiesfras. Additionally you will want to compress the enviornmental data which in the long format is reported for every single tree to just a single value for each site. To do this you use the exact same approach as the `tapply` with the species cover values but use the function `aggregate` instead which works across multiple columns simultaneously (i.e., all the enviornmental variables).
