### ISSUE TITLE
Question 2 on Univariate Assignment

### ISSUE THREAD

**Issue by mosscr** [dmcglinn/quant_methods#62]
I don't really understand what the question is wanting us to do or even how to do it. I can't find it in the lesson anywhere. 

Also, when I run the anova function, it is not giving me any r-squared values or p-values. Does anyone know why this is?

**Comment by dmcglinn** [comment]
Hey @mosscr the question is asking you to refit the models you considered in question 1 but with a poisson rather than gaussian error distribution. I think the question makes it pretty clear how to fit those models using the function `glm` which works just like the function `lm` except there is an additional argument called `family` where you can specify the error distribution. The `anova` function will not return R-squared values or p-values you are correct. It will only returned sums of squares for the fitted and residual portions of the model. If you want p-values for individual terms then I suggest you use the functions `summary` or `car::Anova`. If you use `Anova` from the `car` package then I suggest using type III anova comparisons as I pointed out in the question. For R2 values for a not OLS model you will have to use the formula I provided in the question to compute a pusedo R2 value. This is because strictly speaking R2 is only defined for OLS models.

**Comment by mosscr** [comment]
I think I got the data into the glm model, but I have tried to input the glm into the pseduo r2 formula following what is on the assignment and I don't get any output.

**Comment by dmcglinn** [comment]
Can you post your code please so we can try to help. It should be working.

**Comment by mosscr** [comment]
pseudo_r2 <- function(acer_poi) {
    1 - acer_poi$deviance / acer_poi$null.deviance
}

This is what I was inputting. The acer_poi gives me an output for my data when I run that, but the pseudo r2 just spits back out the code.

**Comment by dmcglinn** [comment]
So the function `psuedo_r2` as defined in the question is 
```r
pseudo_r2 = function(glm_mod) {
                1 -  glm_mod$deviance / glm_mod$null.deviance
            }
```
The argument this function requires is `glm_mod` which is the fitted glm model not the data frame for acer. Just so it is clear when you use a function you don't change the function you just supply it what you need. So for example I can now use

```r
my_mod <- glm( cover ~ elev, data = my_data, family = 'poisson')
psuedo_r2(my_mod)
```

**Comment by dmcglinn** [comment]
PS `my_mod` is a terrible name and you should avoid silly uninformative names like that for your objects ;P

**Comment by mosscr** [comment]
I got a value for the pseudo r2! Thank you so much!
