### ISSUE TITLE
Univariate - interpreting pseudo r^2

### ISSUE THREAD

**Issue by jacksonbarrattheitmann** [dmcglinn/quant_methods#70]
We talked about this briefly in class, but my pseudo r^2 value is still super high for the Abies model, whereas for the Acer model it remains about the same as what's calculated using the lm model. I could just use the AIC, but then I can't compare it to values obtained in the lm model.  
```{r}
acer_poi <- glm(acer$cover~acer$elev+acer$tci+acer$beers+acer$disturb, family='poisson')

summary(acer_poi)

acer_poi_r2 <- (1 - acer_poi$deviance/acer_poi$null.deviance)
print(acer_poi_r2)



abies_poi <- glm(abies$cover~abies$elev+abies$streamdist+abies$disturb+abies$tci, 
      family='poisson')

summary(abies_poi)


abies_poi_r2 <- (1 - abies_poi$deviance/abies_poi$null.deviance)

print(abies_poi_r2)
'''

**Comment by dmcglinn** [comment]
Hey @jacksonbarrattheitmann I took another look at this and I also found this signal. In class today,  I got confused and thought you were saying the OLS was better for the abies species, but I realize now that you actually meant that OLS (i.e., Gaussian) was better than or as good as Poisson for acer but that Poisson was much better for abies. These results all make sense when we consider a few different facts: 
1) Poisson will converge on the Gaussian error distribution as the mean increases so for Acer which has an average cover pretty far from zero it is reasonable that Poisson and Gaussian models are converging, but
2) Abies on the other hand is absent from most sites all these zeros are difficult for the Gaussian model to deal with because it will often predict negative cover (which makes no sense in the real world). In this context in which most sites are zero a Poisson, Negative Binomial, or zero-inflated Poisson will do a better job. 

When I post the solutions file for this week I'll work though these other modeling approaches as well.
