### ISSUE TITLE
Knitting Homework #3

### ISSUE THREAD

**Issue by Regan-Honeycutt** [dmcglinn/quant_methods#71]
Hi everyone! I am having trouble knitting Homework #3. Everytime I knit, the file is about to save, and then I get the following error:

File ../smokies_transects.png not found in resource path
Error: pandoc document conversion failed with error 99
Execution halted

Does anyone know how I can resolve this?

**Comment by Timara-Vereen** [comment]
I am also having this same problem, however, R Studio is giving me this error

**Comment by dmcglinn** [comment]
Hey folks so essentially what is happening is that you copy and pasted my assignment and included this line in your .Rmd file. Delete the following line
```r
![](../smokies_transects.png) 
```
That line is trying to find the file: `smokies_transects.png` but it can't find it because you don't have it in your local directory. 

Also delete other unnecessary information. Try to keep your homework clean.
