### ISSUE TITLE
Spatial HW Q: Variogram

### ISSUE THREAD

**Issue by RylieTalmadge** [dmcglinn/quant_methods#79]
For some reason, no matter what I do or install, I can't get the variogram function to work. Any tips?

**Comment by dmcglinn** [comment]
Hey @RylieTalmadge one key thing is that it is a little strange because the first letter is capitalized. Also you have to load the package `nlme` so for example try: 

```?nlme::Variogram```

and see if that pulls up the help file for the function. If so then you at least know that the software is installed. If you have specific question about how to use the function the post that to this thread.
