### ISSUE TITLE
Interesting pvalues

### ISSUE THREAD

**Issue by claydustin** [dmcglinn/quant_methods#9]
So I was messing around...

freq = apply(BCI, 2, sum)
sort_indices = sort(freq, decreasing = FALSE, index.return = TRUE)$ix
xy_dist = dist(BCI.env[,c(1,2)])

mantel_cor = c()

for(i in 1:length(freq)){ 
    ar_dist = dist(BCI[,sort_indices[i]])
    mantel_cor[i] = mantel(xy_dist, ar_dist)$signif
}

So mantel_cor returns a vector of all the p-values ordered according to frequency so mantel_cor[1] is the correlation for the rarest species. 

Now the funky part. try 

plot(mantel_cor) this will plot the mantel correlation on frequency.....there appears to be no correlation. THERE SHOULD BE!

**Comment by friedrichknuth** [comment]
Are you assuming that rare species are more highly spatially correlated to each other? Do you have proof for this phenomenon?

**Comment by claydustin** [comment]
The only thing im assuming is that there should be some correlation between
how frequent a special appears and it's spatial dependence. Not saying that
it should be exclusively positive or negative but that it should be at
least one of them.
Am 20.02.2015 13:57 schrieb "friedrichknuth" <notifications@github.com>:

**Comment by friedrichknuth** [comment]
From going through Q1 and looking at the slope of spatial distance (x) vs difference in abundance (y), I saw varying trends amongst plot observations for both rare and common species. Thus, both expressed a spatial dependence, but neither were consistent in the direction of slope, i.e. spatial pattern with distance.

Thus, if you are plotting just the P value, representing the correlation to change in spatial distance, vs spatial distance, it may not reflect a visible trend between species.

**Comment by claydustin** [comment]
So it's a bit confusing. But the pvalues  are a list of regression
coefficients associated with the frequency (or abundance) of a soecies. So
the pvalue at the the bottom of the matrix (1.2.3. Etc) are the least
abundant pvalues for spatial dependence and the upper values are pvalues
for the most common. You showed me Variations in your slopes which is to be
expected but their should be some pattern in the pvalues based on
frequency. He said in class it is to expected that rarer soecies would be
more spatially dependent than less rare species.  Im pretty confident in
the logic of my code just perhaps not the Syntax. Thanks for the discussion
Friedrich!
Am 20.02.2015 14:20 schrieb "friedrichknuth" <notifications@github.com>:

**Comment by claydustin** [comment]
I just reread your post. We are saying essentially the same thing. But from
class Dan said typically rarer show more correlation than common. :)
Am 20.02.2015 14:20 schrieb "friedrichknuth" <notifications@github.com>:

**Comment by friedrichknuth** [comment]
Right - the only "evidence" we have for expecting a clear trend in rare vs common is what Dan implied, but there doesn't seem to be a distinct pattern. Abundance within a given species varies with distance, but the nature of its variance (increase or decrease in abundance) seems unrelated to its overall relative abundance (rare vs common).

**Comment by dmcglinn** [comment]
Great discussion @claydustin and @friedrichknuth ! Great job putting some code together to look at this @claydustin . I posted a gist of your code snippet with small changes to make it a bit more readable. The keep difference was plotting the p-values as a function of abundance (i.e., `freq`) rather than just `plot(mantel.cor)`

https://gist.github.com/dmcglinn/f93c04da2c3c398c35be

A relationship is weak to non-existent. If you take a look at the actual correlation values you see a similar pattern but it is perhaps a bit more interesting because it emphases that abundant species tend to have positive relationships where as the rare species are much more variable. 

Ecological theory suggests species should tend to typically be aggregated (i.e., a positive slope in this case). Theory is much less clear if this should track abundance and in what way but I think these results are pretty interesting as a first cut. One thing to note is that the raw BCI dataset has spatial coordinates of every tree so space can be treated as continuous rather than using these coarse discrete quadrats we are using.  Thanks for sharing!

**Comment by dmcglinn** [comment]
I updated my gist to use Bray-Curtis distance rather than Euclidean and a bit more a of a pattern pops out. I was curious to try this because ecologists generally argue that for species composition euclidean distance is not preferred because of the double-zero problem (Numerical Ecology in R - p32).
